apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: reconfigure-1-nothing
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: standalone
  timeout: 5m
  apply: IfReady



